## 国际化文本管理 - ui_text.gd
## 作用: 存储中英文界面文本，根据语言设置返回对应翻译
## 独立模块，不依赖其他脚本

extends RefCounted

const LANG_ZH = "zh"
const LANG_EN = "en"

const DATA = {
	LANG_EN: {
		"language_title": "SELECT LANGUAGE",
		"language_subtitle": "Choose before entering motor control",
		"language_zh": "Chinese / 中文",
		"language_en": "English",
		"language_shutdown": "Shutdown",
			"language_hint": "D-PAD select   A confirm   B exit",
		"node_title": "SELECT NODE",
		"node_subtitle": "Enter one CANopen node before opening control UI",
		"node_range": "Valid range: 1 - 127",
		"node_hint": "D-PAD move   A input/confirm   B/BACK language",
		"node_error_empty": "Enter node id",
		"node_error_range": "Node must be 1 - 127",
		"node_selected_status": "NODE %d selected",
		"app_title": "AGV MOTOR DIAGNOSTIC TERMINAL",
		"header_subtitle": "RGB30 | 720*720 | CANopen over UDP | Node%d",
		"tab_monitor": "MONITOR",
		"tab_config": "CONFIG",
		"tab_ota": "OTA",
		"tab_can": "CAN LOG",
		"cmd_enable": "ENABLE",
		"cmd_disable": "DISABLE",
		"cmd_estop": "E-STOP",
		"cmd_jog_cw": "JOG CW",
		"cmd_jog_ccw": "JOG CCW",
		"cfg_mode": "Mode",
		"cfg_control_word": "Control Word",
		"cfg_target_speed": "Target Speed",
		"cfg_target_torque": "Target Torque",
		"cfg_pid_kp": "PID Kp",
		"cfg_pid_ki": "PID Ki",
		"cfg_pid_kd": "PID Kd",
		"cfg_current_limit": "Current Limit",
		"cfg_save_eeprom": "Save EEPROM",
		"cfg_drive_mode": "drive mode",
		"cfg_cia_402": "CiA 402",
		"cfg_rpm": "rpm",
		"cfg_permille": "permille",
		"cfg_proportional": "proportional",
		"cfg_integral": "integral",
		"cfg_derivative": "derivative",
		"cfg_amps": "amps",
		"cfg_persist": "persist",
		"ota_load": "LOAD FIRMWARE",
		"ota_send": "SEND TO DONGLE",
		"ota_verify": "VERIFY MD5",
		"ota_flash": "FLASH MOTOR",
		"ota_upload": "UPLOAD MODE",
		"commands": "COMMANDS",
		"telemetry": "REAL-TIME TELEMETRY",
		"metric_current": "CURRENT",
		"metric_voltage": "VOLTAGE",
		"metric_speed": "SPEED",
		"metric_position": "POSITION",
		"metric_torque": "TORQUE",
		"metric_status": "STATUS",
		"waveform": "CURRENT WAVEFORM",
		"waiting_packets": "Waiting for motor_status packets...",
		"hotkeys": "HOTKEYS",
		"input": "INPUT",
		"last": "LAST",
		"config_header": "OBJECT DICTIONARY        A READ SELECTED  D-PAD NAVIGATE  START PAGE",
		"sdo_result": "SDO RESULT",
		"no_sdo": "No SDO transaction",
		"no_firmware": "No firmware loaded",
		"copy_firmware": "Copy firmware to /storage/firmware.bin",
		"firmware_update": "FIRMWARE UPDATE        STATUS: %s  |  %s",
		"ota_upload_panel": "UPLOAD FIRMWARE MODE",
		"ota_upload_hint": "A open browser upload screen",
		"transfer_state": "TRANSFER STATE: %s",
		"target_dongle": "Target: ESP32 CAN Dongle 192.168.4.1:5000",
		"ota_log": "OTA LOG",
		"ota_log_line": "OTA LOG: %s",
		"can_filter": "INPUT",
		"can_reset": "RESET LOG",
		"can_pause": "PAUSE",
		"can_run": "RUN",
		"can_filter_label": "FILTER",
		"can_header": "CAN LOG        A INPUT FILTER  D-PAD NAVIGATE  START PAGE",
		"can_all": "all CAN / UDP packets",
		"can_log": "CAN / UDP LOG",
		"can_empty": "No CAN / UDP packets",
		"can_paused": "PAUSED",
		"can_reset_status": "CAN log cleared",
		"can_run_status": "CAN log running",
		"keyboard_title": "QWERTY FILTER INPUT",
		"keyboard_hint": "D-PAD move   A input   B close",
		"upload_title": "FIRMWARE UPLOAD MODE",
		"upload_subtitle": "Connect your computer to RGB30 hotspot, then open the upload URL.",
		"upload_mode_label": "NETWORK MODE",
		"upload_mode_value": "UPLOAD HOTSPOT",
		"upload_wifi": "Wi-Fi SSID",
		"upload_password": "Wi-Fi password",
		"upload_url": "Open in browser",
		"upload_save_path": "Firmware will be saved as",
		"upload_status": "Upload service",
		"upload_exit": "BACK TO OTA PAGE",
		"upload_starting": "Starting upload mode...",
		"upload_ready": "Upload mode ready",
		"upload_fallback": "Hotspot failed, using current Wi-Fi",
		"upload_script_missing": "Upload script not deployed",
		"upload_mode_status": "Upload mode opened",
		"upload_restore_status": "Dongle mode restored",
		"footer": "START page   D-PAD select   A execute   B stop   X enable   Y disable   L2 E-STOP   SELECT language",
	},
	LANG_ZH: {
		"language_title": "选择语言 / SELECT LANGUAGE",
		"language_subtitle": "进入电机控制系统前选择界面语言",
		"language_zh": "Chinese / 中文",
		"language_en": "English",
		"language_shutdown": "关机",
			"language_hint": "方向键选择   A 确认   B 退出",
		"node_title": "选择节点",
		"node_subtitle": "进入控制界面前输入 CANopen 节点",
		"node_range": "范围: 1 - 127",
		"node_hint": "方向键选择   A 输入/确认   B/BACK 返回语言",
		"node_error_empty": "请输入节点",
		"node_error_range": "节点范围 1 - 127",
		"node_selected_status": "已选择节点 %d",
		"app_title": "AGV 电机诊断终端",
		"header_subtitle": "RGB30 | 720*720 | CANopen over UDP | 节点%d",
		"tab_monitor": "监控",
		"tab_config": "配置",
		"tab_ota": "升级",
		"tab_can": "CAN日志",
		"cmd_enable": "使能",
		"cmd_disable": "失能",
		"cmd_estop": "急停",
		"cmd_jog_cw": "正转点动",
		"cmd_jog_ccw": "反转点动",
		"cfg_mode": "模式",
		"cfg_control_word": "控制字",
		"cfg_target_speed": "目标速度",
		"cfg_target_torque": "目标转矩",
		"cfg_pid_kp": "PID Kp",
		"cfg_pid_ki": "PID Ki",
		"cfg_pid_kd": "PID Kd",
		"cfg_current_limit": "电流限制",
		"cfg_save_eeprom": "保存 EEPROM",
		"cfg_drive_mode": "驱动模式",
		"cfg_cia_402": "CiA 402",
		"cfg_rpm": "rpm",
		"cfg_permille": "千分比",
		"cfg_proportional": "比例",
		"cfg_integral": "积分",
		"cfg_derivative": "微分",
		"cfg_amps": "安培",
		"cfg_persist": "持久化",
		"ota_load": "加载固件",
		"ota_send": "发送到网关",
		"ota_verify": "校验 MD5",
		"ota_flash": "刷写电机",
		"ota_upload": "上传模式",
		"commands": "命令",
		"telemetry": "实时遥测",
		"metric_current": "电流",
		"metric_voltage": "电压",
		"metric_speed": "速度",
		"metric_position": "位置",
		"metric_torque": "转矩",
		"metric_status": "状态",
		"waveform": "电流波形",
		"waiting_packets": "等待 motor_status 数据包...",
		"hotkeys": "快捷键",
		"input": "输入",
		"last": "最近",
		"config_header": "对象字典        A 读取选中项  方向键导航  START 切页",
		"sdo_result": "SDO 结果",
		"no_sdo": "暂无 SDO 事务",
		"no_firmware": "未加载固件",
		"copy_firmware": "复制固件到 /storage/firmware.bin",
		"firmware_update": "固件升级        状态: %s  |  %s",
		"ota_upload_panel": "上传固件模式",
		"ota_upload_hint": "A 打开上传提示界面",
		"transfer_state": "传输状态: %s",
		"target_dongle": "目标: ESP32 CAN 网关 192.168.4.1:5000",
		"ota_log": "OTA 日志",
		"ota_log_line": "OTA 日志: %s",
		"can_filter": "过滤字段",
		"can_reset": "清空日志",
		"can_pause": "暂停",
		"can_run": "继续",
		"can_filter_label": "过滤",
		"can_header": "CAN 消息接收        A 输入过滤  方向键选择  START 切页",
		"can_all": "全部 CAN / UDP 消息",
		"can_log": "CAN / UDP 日志",
		"can_empty": "暂无 CAN / UDP 消息",
		"can_paused": "暂停",
		"can_reset_status": "CAN 日志已清空",
		"can_run_status": "CAN 日志继续接收",
		"keyboard_title": "QWERTY 过滤输入",
		"keyboard_hint": "方向键选择   A 输入   B 关闭",
		"upload_title": "固件上传模式",
		"upload_subtitle": "电脑连接 RGB30 热点后，在浏览器打开上传网址。",
		"upload_mode_label": "网络模式",
		"upload_mode_value": "上传热点",
		"upload_wifi": "Wi-Fi 名称",
		"upload_password": "Wi-Fi 密码",
		"upload_url": "浏览器打开",
		"upload_save_path": "固件保存为",
		"upload_status": "上传服务",
		"upload_exit": "返回 OTA 界面",
		"upload_starting": "正在启动上传模式...",
		"upload_ready": "上传模式已就绪",
		"upload_fallback": "热点启动失败，使用当前 Wi-Fi",
		"upload_script_missing": "上传脚本未部署",
		"upload_mode_status": "已打开上传模式",
		"upload_restore_status": "已恢复 DONGLE 模式",
		"footer": "START 切页   方向键选择   A 执行   B 停止   X 使能   Y 失能   L2 急停   SELECT 语言",
	},
}


static func text(lang: String, key: String) -> String:
	var table = DATA.get(lang, DATA[LANG_EN])
	return str(table.get(key, DATA[LANG_EN].get(key, key)))
