## 国际化文本管理 - ui_text.gd
## 作用: 存储中英文界面文本，根据语言设置返回对应翻译
## 独立模块，不依赖其他脚本

extends RefCounted

const LANG_ZH = "zh"
const LANG_EN = "en"

const DATA = {
	LANG_EN: {
		"language_title": "SELECT LANGUAGE",
		"language_subtitle": "Choose before entering motor control",
		"language_zh": "Chinese",
		"language_en": "English",
		"language_hint": "D-PAD select   A confirm",
		"app_title": "AGV MOTOR DIAGNOSTIC TERMINAL",
		"header_subtitle": "RGB30 | 720*720 | CANopen over UDP | Node%d",
		"tab_monitor": "MONITOR",
		"tab_config": "CONFIG",
		"tab_ota": "OTA",
		"cmd_enable": "ENABLE",
		"cmd_disable": "DISABLE",
		"cmd_estop": "E-STOP",
		"cmd_jog_cw": "JOG CW",
		"cmd_jog_ccw": "JOG CCW",
		"cfg_mode": "Mode",
		"cfg_control_word": "Control Word",
		"cfg_target_speed": "Target Speed",
		"cfg_target_torque": "Target Torque",
		"cfg_pid_kp": "PID Kp",
		"cfg_pid_ki": "PID Ki",
		"cfg_pid_kd": "PID Kd",
		"cfg_current_limit": "Current Limit",
		"cfg_save_eeprom": "Save EEPROM",
		"cfg_drive_mode": "drive mode",
		"cfg_cia_402": "CiA 402",
		"cfg_rpm": "rpm",
		"cfg_permille": "permille",
		"cfg_proportional": "proportional",
		"cfg_integral": "integral",
		"cfg_derivative": "derivative",
		"cfg_amps": "amps",
		"cfg_persist": "persist",
		"ota_load": "LOAD FIRMWARE",
		"ota_send": "SEND TO DONGLE",
		"ota_verify": "VERIFY MD5",
		"ota_flash": "FLASH MOTOR",
		"commands": "COMMANDS",
		"telemetry": "REAL-TIME TELEMETRY",
		"metric_current": "CURRENT",
		"metric_voltage": "VOLTAGE",
		"metric_speed": "SPEED",
		"metric_position": "POSITION",
		"metric_torque": "TORQUE",
		"metric_status": "STATUS",
		"waveform": "CURRENT WAVEFORM",
		"waiting_packets": "Waiting for motor_status packets...",
		"hotkeys": "HOTKEYS",
		"input": "INPUT",
		"last": "LAST",
		"config_header": "OBJECT DICTIONARY        A READ SELECTED  D-PAD NAVIGATE  START PAGE",
		"sdo_result": "SDO RESULT",
		"no_sdo": "No SDO transaction",
		"no_firmware": "No firmware loaded",
		"copy_firmware": "Copy firmware to /storage/firmware.bin",
		"firmware_update": "FIRMWARE UPDATE        STATUS: %s  |  %s",
		"transfer_state": "TRANSFER STATE: %s",
		"target_dongle": "Target: ESP32 CAN Dongle 192.168.4.1:5000",
		"ota_log": "OTA LOG",
		"ota_log_line": "OTA LOG: %s",
		"footer": "START page   D-PAD select   A execute   B stop   X enable   Y disable   L2/SEL E-STOP",
	},
	LANG_ZH: {
		"language_title": "选择语言 / SELECT LANGUAGE",
		"language_subtitle": "进入电机控制系统前选择界面语言",
		"language_zh": "中文版",
		"language_en": "English",
		"language_hint": "方向键选择   A 确认",
		"app_title": "AGV 电机诊断终端",
		"header_subtitle": "RGB30 | 720*720 | CANopen over UDP | 节点%d",
		"tab_monitor": "监控",
		"tab_config": "配置",
		"tab_ota": "升级",
		"cmd_enable": "使能",
		"cmd_disable": "失能",
		"cmd_estop": "急停",
		"cmd_jog_cw": "正转点动",
		"cmd_jog_ccw": "反转点动",
		"cfg_mode": "模式",
		"cfg_control_word": "控制字",
		"cfg_target_speed": "目标速度",
		"cfg_target_torque": "目标转矩",
		"cfg_pid_kp": "PID Kp",
		"cfg_pid_ki": "PID Ki",
		"cfg_pid_kd": "PID Kd",
		"cfg_current_limit": "电流限制",
		"cfg_save_eeprom": "保存 EEPROM",
		"cfg_drive_mode": "驱动模式",
		"cfg_cia_402": "CiA 402",
		"cfg_rpm": "rpm",
		"cfg_permille": "千分比",
		"cfg_proportional": "比例",
		"cfg_integral": "积分",
		"cfg_derivative": "微分",
		"cfg_amps": "安培",
		"cfg_persist": "持久化",
		"ota_load": "加载固件",
		"ota_send": "发送到网关",
		"ota_verify": "校验 MD5",
		"ota_flash": "刷写电机",
		"commands": "命令",
		"telemetry": "实时遥测",
		"metric_current": "电流",
		"metric_voltage": "电压",
		"metric_speed": "速度",
		"metric_position": "位置",
		"metric_torque": "转矩",
		"metric_status": "状态",
		"waveform": "电流波形",
		"waiting_packets": "等待 motor_status 数据包...",
		"hotkeys": "快捷键",
		"input": "输入",
		"last": "最近",
		"config_header": "对象字典        A 读取选中项  方向键导航  START 切页",
		"sdo_result": "SDO 结果",
		"no_sdo": "暂无 SDO 事务",
		"no_firmware": "未加载固件",
		"copy_firmware": "复制固件到 /storage/firmware.bin",
		"firmware_update": "固件升级        状态: %s  |  %s",
		"transfer_state": "传输状态: %s",
		"target_dongle": "目标: ESP32 CAN 网关 192.168.4.1:5000",
		"ota_log": "OTA 日志",
		"ota_log_line": "OTA 日志: %s",
		"footer": "START 切页   方向键选择   A 执行   B 停止   X 使能   Y 失能   L2/SEL 急停",
	},
}


static func text(lang: String, key: String) -> String:
	var table = DATA.get(lang, DATA[LANG_EN])
	return str(table.get(key, DATA[LANG_EN].get(key, key)))
